### ISSUE TITLE
Pasting in code block

### ISSUE THREAD

**Issue by yekm** [danloh/mdSilo-web#109]
* Create code block
* Paste multiline text from another application
* Every line appears as separate code block

![2022-01-24-171415_708x448_scrot](https://user-images.githubusercontent.com/205196/150798957-7d703eba-1509-428d-8acb-639b2f8b9af7.png)

archlinux, google-chrome 96.0.4664.110

**Comment by yekm** [comment]
Pasting from the "Preview" tab from github works fine. So the issue is only with text without metadata (from textinput or terminal)

**Comment by danloh** [comment]
Thanks. Also found same issue on Pasting in quote block. 

Will investigate this.

**Comment by danloh** [comment]
@yekm I fixed it in #130 . Let me know if it works well.  Thanks.

**Comment by yekm** [comment]
works well. Thanks.
